cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('added/<int:product_id>/', views.single_cart_add, name='single_cart_add'),
    path('product/add/<int:product_id>/', views.add_to_card_from_product_page, name='add_to_card_from_product_page'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

products/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from cart import views
from products.views import ProductTemplate, ProductDetailView, AddReview, WishlistModelListView, add_to_wishlist, \
    CartModelListView, add_to_cart, load_more_data, ProductListAPIView, ProductDiscountAPIView, ProductDetailAPIView, \
    ProductFilterListAPIView, ProductBrandFilterListAPIView

app_name = 'product'

urlpatterns = [
    path('', ProductTemplate.as_view(), name='products'),
    path('<int:pk>/', ProductDetailView.as_view(), name='single'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('products/<int:pk>/', AddReview.as_view(), name='add_review'),
    path('wishlist/', WishlistModelListView.as_view(), name='wishlist'),
    path('wishlist/<int:pk>/', add_to_wishlist, name='add-wishlist'),
    path('cart/', CartModelListView.as_view(), name='cart'),
    path('cart/<int:pk>/', add_to_cart, name='add-cart'),
    path('api/v1/products/', ProductListAPIView.as_view(), name='products'),
    path('api/v1/products/filters-category', ProductFilterListAPIView.as_view(), name='products-filter'),
    path('api/v1/products/filters-brand', ProductBrandFilterListAPIView.as_view(), name='products-filter-brand'),
    path('api/v1/discount/', ProductDiscountAPIView.as_view()),
    path('api/v1/products/<int:pk>/', ProductDetailAPIView.as_view()),

    # path('carts/<int:pk>/', create_carts, name='create-carts'),
]

teiler/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.routers import DefaultRouter
from cart import views
from help.views import HelpListView
from products.serializers import ReviewCreateSerializer
from products.views import HomeTemplate, AboutTemplateView, ContactTemplateView, OrderTemplateView, load_more_data, \
    ProductListAPIView, ProductRatingAPIView, CarouselListAPIView, HelpListAPIView, CategoryListAPIView, \
    ProductDetailAPIView, CountryListAPIView, ProductImageModelAPIView, ProductDiscountAPIView, \
    ReviewModelSerializerListAPIView, AddRatingViewSet
from user.views import edit_account_view, update_username, update_phone, update_email, update_date, \
    update_male, UserViewSet, UserDetailAPIView, UserProductDetail, TokenCreateView, LogoutView, UpdateProfileView, \
    GetProfileView, MyTokenObtainPairView, LoginAPIView, UserNewCreateView
from orders.views import user_order_view, UserAPIListView, OrderAPIListView
from .yasg import urlpatterns as doc_urls


router = DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('products/', include('products.urls',  namespace='product')),
    path('about/', AboutTemplateView.as_view(), name='abouts'),
    path('contacts/', ContactTemplateView.as_view(), name='contacts'),
    path('articles/', HelpListView.as_view(), name='articles'),
    path('order/', OrderTemplateView.as_view(), name='order'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('reviews/', include('orders.urls', namespace='reviews')),
    path('profile/<int:user_pk>', user_order_view, name='profile'),
    path('profilw_edit/<user_id>/edit/', edit_account_view, name='edit'),
    path('change_username/<user_id>/edit/', update_username, name='update_username'),
    path('change_phone/<user_id>/edit/', update_phone, name='update_phone'),
    path('change_email/<user_id>/edit/', update_email, name='update_email'),
    path('change_date/<user_id>/edit/', update_date, name='update_date'),
    path('change_male/<user_id>/edit/', update_male, name='update_male'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('load-more-data/', load_more_data, name='load_more_data'),
    # path('api/v1/auth/', include('djoser.urls.authtoken')),
    # path('api/v1/auth/login/', TokenCreateView.as_view()),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/cities/', CountryListAPIView.as_view()),
    path('users/', include('user.urls')),
    # path('reviewssss/', include('orders.urls', namespace='orders22')),

    path('api/v1/carousels', CarouselListAPIView.as_view()),
    path('api/v1/help', HelpListAPIView.as_view()),
    path('api/v1/categories', CategoryListAPIView.as_view()),
    path('authorizations/', include('authorization.urls')),
    # path('api2/users/', UserAPIListView.as_view()),
    # path('api2/user-order/', OrderAPIListView.as_view()),
    path('', HomeTemplate.as_view())
]

urlpatterns += doc_urls
urlpatterns += router.urls

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

{% include 'layouts/header.html' %}

{% block content %}
{% endblock %}

{% include 'layouts/footer.html' %}

<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=2026287c-0c43-4518-8bf4-eabcdec6536a" type="text/javascript"></script>
<script src="https://yandex.st/jquery/2.2.3/jquery.min.js" type="text/javascript"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/bundle.js' %}"></script>
{% block extra_js %}
{% endblock extra_js %}
</body>
</html>

templates/layouts/header.html
{% load static %}
{% load new_tags %}
{% load i18n %}
<div class="container o-visible">
        <header class="header">
    <div class="header__top">
        <div class="header__top_contacts">
            <button class="geo" data-micromodal-trigger="city">
                Москва
            </button>
            <a href="tel:+79223543232" class="tel">+7 (922) 354 32 32</a>
        </div>
        <ul class="header__top_nav">
            <li>
                <a href="{% url 'contacts' %}" class="header__top_nav_item">Контакты</a>
            </li>
            <li>
                <a href="{% url 'product:products' %}" class="header__top_nav_item">Акции</a>
            </li>
            <li>
                <a href="{% url 'articles' %}" class="header__top_nav_item">Помощь</a>
            </li>
            <li>
                <a href="{% url 'abouts' %}" class="header__top_nav_item">О нас</a>
            </li>
        </ul>
    </div>
    <div class="header__main">
        <a href="/" class="header__main_logo">
            <img src="{% static './img/Logo.svg' %}" alt="Logotype">
        </a>

        <div class="header__main_cat_wr">
            <button id="menuTrigger" class="btn header__main_cat">
            <div class="open">

                <svg width="18" height="18" viewBox="0 0 17 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M2.20413 3.33333C2.20413 2.59695 2.80109 2 3.53747 2H6.20413C6.94051 2 7.53747 2.59695 7.53747 3.33333V6C7.53747 6.73638 6.94051 7.33333 6.20413 7.33333H3.53747C2.80109 7.33333 2.20413 6.73638 2.20413 6V3.33333ZM6.20413 3.33333H3.53747V6H6.20413V3.33333ZM8.8708 3.33333C8.8708 2.59695 9.46775 2 10.2041 2H12.8708C13.6072 2 14.2041 2.59695 14.2041 3.33333V6C14.2041 6.73638 13.6072 7.33333 12.8708 7.33333H10.2041C9.46775 7.33333 8.8708 6.73638 8.8708 6V3.33333ZM12.8708 3.33333H10.2041V6H12.8708V3.33333ZM2.20413 10C2.20413 9.26362 2.80109 8.66667 3.53747 8.66667H6.20413C6.94051 8.66667 7.53747 9.26362 7.53747 10V12.6667C7.53747 13.403 6.94051 14 6.20413 14H3.53747C2.80109 14 2.20413 13.403 2.20413 12.6667V10ZM6.20413 10H3.53747V12.6667H6.20413V10ZM8.8708 10C8.8708 9.26362 9.46775 8.66667 10.2041 8.66667H12.8708C13.6072 8.66667 14.2041 9.26362 14.2041 10V12.6667C14.2041 13.403 13.6072 14 12.8708 14H10.2041C9.46775 14 8.8708 13.403 8.8708 12.6667V10ZM12.8708 10H10.2041V12.6667H12.8708V10Z" fill="white"/>
                </svg>

            </div>
            <div class="close">
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M3.96967 3.96967C4.26256 3.67678 4.73744 3.67678 5.03033 3.96967L9 7.93934L12.9697 3.96967C13.2626 3.67678 13.7374 3.67678 14.0303 3.96967C14.3232 4.26256 14.3232 4.73744 14.0303 5.03033L10.0607 9L14.0303 12.9697C14.3232 13.2626 14.3232 13.7374 14.0303 14.0303C13.7374 14.3232 13.2626 14.3232 12.9697 14.0303L9 10.0607L5.03033 14.0303C4.73744 14.3232 4.26256 14.3232 3.96967 14.0303C3.67678 13.7374 3.67678 13.2626 3.96967 12.9697L7.93934 9L3.96967 5.03033C3.67678 4.73744 3.67678 4.26256 3.96967 3.96967Z" fill="white"/>
                </svg>

            </div>

            <span>Каталог</span>
        </button>
        </div>
        <div class="header__main_search">
            <!-- <div class="header__main_search_drop dropdown">
                <div class="header__main_search_drop_head dropdown_head" data-drophead>
                    Везде
                    <svg data-drophead width="6" height="4" viewBox="0 0 6 4" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path data-drophead d="M1.28101 4.00073C0.77231 4.00073 0.494417 3.40742 0.820081 3.01662L2.87239 0.553851C3.11227 0.265999 3.55438 0.265998 3.79426 0.553851L5.84656 3.01662C6.17223 3.40742 5.89433 4.00073 5.38563 4.00073L1.28101 4.00073Z" fill="#3D5165"/>
                        </svg>

                </div>
                <div class="header__main_search_drop_list dropdown_list">
                    <div class="header__main_search_drop_item dropdown_item" data-droplistitem>Категория 1</div>
                    <div class="header__main_search_drop_item dropdown_item" data-droplistitem>Категория 2</div>
                    <div class="header__main_search_drop_item dropdown_item" data-droplistitem>Категория 3</div>
                </div>
            </div> -->
            <div class="header__main_search_filter">
                <select class="header__main_search_filter_select">
                    <option value="Все">Везде</option>
                    <option value="Категории">Категории</option>
                    <option value="Товары">Товары</option>
                </select>
            </div>

            <form action="{% url 'product:products' %}">
                <input class="header__main_search_input" type="text" name="q" value="{{ request.GET.q }}"  placeholder="Поиск по товарам">
                <button class="header__main_search_btn" type="submit">
                    <svg width="13" height="14" viewBox="0 0 13 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.2 1.38325C3.04609 1.38325 1.3 3.12934 1.3 5.28325C1.3 7.43716 3.04609 9.18325 5.2 9.18325C7.35391 9.18325 9.1 7.43716 9.1 5.28325C9.1 3.12934 7.35391 1.38325 5.2 1.38325ZM0 5.28325C0 2.41137 2.32812 0.083252 5.2 0.083252C8.07188 0.083252 10.4 2.41137 10.4 5.28325C10.4 6.48491 9.9924 7.59138 9.30791 8.47192L12.8096 11.9736C13.0635 12.2275 13.0635 12.639 12.8096 12.8929C12.5558 13.1467 12.1442 13.1467 11.8904 12.8929L8.38867 9.39116C7.50812 10.0757 6.40166 10.4833 5.2 10.4833C2.32812 10.4833 0 8.15513 0 5.28325Z" fill="#0047FF"/>
                        </svg>

                </button>
           </form>
        </div>
        <div class="header__main_btns">

            <a href="{% url 'cart:cart_detail' %}" class="main_btn basket">
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M1.41631 1.33333L2.5054 8.41248C2.51333 8.47091 2.52991 8.5266 2.55381 8.5782C2.62575 8.73353 2.76401 8.85188 2.93226 8.8969C2.98366 8.91071 3.03752 8.91761 3.09262 8.91667H9.50008C9.75769 8.91667 9.98479 8.7477 10.0588 8.50095L11.8088 2.66762C11.8618 2.491 11.8282 2.29973 11.7181 2.15179C11.608 2.00385 11.4345 1.91667 11.2501 1.91667H2.68644L2.49459 0.669613C2.4874 0.617473 2.47332 0.567533 2.4533 0.52074C2.41697 0.435529 2.36132 0.361718 2.29259 0.303863C2.22881 0.250085 2.15335 0.209732 2.07056 0.187159C2.01844 0.172888 1.96377 0.16574 1.90782 0.166668H0.750081C0.427915 0.166668 0.166748 0.427835 0.166748 0.750001C0.166748 1.07217 0.427915 1.33333 0.750081 1.33333H1.41631ZM3.58388 7.75L2.86593 3.08333H10.4661L9.06606 7.75H3.58388Z" fill="#242424"/>
                <path d="M4.83341 10.6667C4.83341 11.311 4.31108 11.8333 3.66675 11.8333C3.02242 11.8333 2.50008 11.311 2.50008 10.6667C2.50008 10.0223 3.02242 9.5 3.66675 9.5C4.31108 9.5 4.83341 10.0223 4.83341 10.6667Z" fill="#242424"/>
                <path d="M10.0834 10.6667C10.0834 11.311 9.56108 11.8333 8.91675 11.8333C8.27242 11.8333 7.75008 11.311 7.75008 10.6667C7.75008 10.0223 8.27242 9.5 8.91675 9.5C9.56108 9.5 10.0834 10.0223 10.0834 10.6667Z" fill="#242424"/>
                </svg>

                <span>Корзина</span>
                <span class="ind" id="cart_count">{% get_cart_count request %}</span>
            </a>
            <a href="{% url 'product:wishlist' %}" class="main_btn favourite">
                <svg width="10" height="12" viewBox="0 0 10 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M0 1.167C0 0.522484 0.522483 0 1.167 0H8.169C8.81351 0 9.336 0.522483 9.336 1.167V11.0865C9.336 11.3051 9.21384 11.5053 9.0195 11.6053C8.82515 11.7053 8.59121 11.6884 8.41335 11.5613L4.668 8.88606L0.922652 11.5613C0.744793 11.6884 0.510848 11.7053 0.316501 11.6053C0.122154 11.5053 0 11.3051 0 11.0865V1.167ZM8.169 1.167L1.167 1.167V9.95265L4.32885 7.69419C4.53173 7.54927 4.80427 7.54927 5.00715 7.69419L8.169 9.95265V1.167Z" fill="#242424"/>
                </svg>
                <span>Избранное</span>
                <span class="ind" id="like_count">{% get_wishlist_count request %}</span>
            </a>
            <div  class="main_btn login">
                 {% if user.is_authenticated %}
                    <a href="{% url 'profile' user.pk %}">
                             <svg width="11" height="12" viewBox="0 0 11 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.2515 1.167C3.96247 1.167 2.9175 2.21197 2.9175 3.501C2.9175 4.79003 3.96247 5.835 5.2515 5.835C6.54053 5.835 7.5855 4.79003 7.5855 3.501C7.5855 2.21197 6.54053 1.167 5.2515 1.167ZM1.7505 3.501C1.7505 1.56745 3.31795 0 5.2515 0C7.18505 0 8.7525 1.56745 8.7525 3.501C8.7525 5.43455 7.18505 7.002 5.2515 7.002C3.31795 7.002 1.7505 5.43455 1.7505 3.501ZM2.9175 9.336C1.95073 9.336 1.167 10.1197 1.167 11.0865C1.167 11.4088 0.905758 11.67 0.5835 11.67C0.261242 11.67 0 11.4088 0 11.0865C0 9.47521 1.30621 8.169 2.9175 8.169H7.5855C9.19679 8.169 10.503 9.47521 10.503 11.0865C10.503 11.4088 10.2418 11.67 9.9195 11.67C9.59724 11.67 9.336 11.4088 9.336 11.0865C9.336 10.1197 8.55227 9.336 7.5855 9.336H2.9175Z" fill="#242424"/>
                        </svg>
                         <p style="color: #0047FF">{{user.username}}</p>
                    </a>
                    {% else %}
                    <a href="{% url 'login' %}">
                        <svg width="11" height="12" viewBox="0 0 11 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.2515 1.167C3.96247 1.167 2.9175 2.21197 2.9175 3.501C2.9175 4.79003 3.96247 5.835 5.2515 5.835C6.54053 5.835 7.5855 4.79003 7.5855 3.501C7.5855 2.21197 6.54053 1.167 5.2515 1.167ZM1.7505 3.501C1.7505 1.56745 3.31795 0 5.2515 0C7.18505 0 8.7525 1.56745 8.7525 3.501C8.7525 5.43455 7.18505 7.002 5.2515 7.002C3.31795 7.002 1.7505 5.43455 1.7505 3.501ZM2.9175 9.336C1.95073 9.336 1.167 10.1197 1.167 11.0865C1.167 11.4088 0.905758 11.67 0.5835 11.67C0.261242 11.67 0 11.4088 0 11.0865C0 9.47521 1.30621 8.169 2.9175 8.169H7.5855C9.19679 8.169 10.503 9.47521 10.503 11.0865C10.503 11.4088 10.2418 11.67 9.9195 11.67C9.59724 11.67 9.336 11.4088 9.336 11.0865C9.336 10.1197 8.55227 9.336 7.5855 9.336H2.9175Z" fill="#242424"/>
                        </svg>
                        <span>Войти</span>
                    </a>
                 {% endif %}
            </div>

        </div>


    </div>

    <div class="header__menu" id="mainMenu">
        <div class="header__menu_aside scroll">
            <ul class="header__menu_aside_list">
                {% for category in categories %}
                <li class="header__menu_aside_item">
                    {{ category.title }}
                </li>
                {% endfor %}
            </ul>
        </div>
           {% for category in categories %}
        <div class="header__menu_body scroll">
            <button class="menuclose" data-menuclose>
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M3.96967 3.96967C4.26256 3.67678 4.73744 3.67678 5.03033 3.96967L9 7.93934L12.9697 3.96967C13.2626 3.67678 13.7374 3.67678 14.0303 3.96967C14.3232 4.26256 14.3232 4.73744 14.0303 5.03033L10.0607 9L14.0303 12.9697C14.3232 13.2626 14.3232 13.7374 14.0303 14.0303C13.7374 14.3232 13.2626 14.3232 12.9697 14.0303L9 10.0607L5.03033 14.0303C4.73744 14.3232 4.26256 14.3232 3.96967 14.0303C3.67678 13.7374 3.67678 13.2626 3.96967 12.9697L7.93934 9L3.96967 5.03033C3.67678 4.73744 3.67678 4.26256 3.96967 3.96967Z" fill="#000"/>
                </svg>
            </button>
            <div class="menu_col">
                <div class="menu_col_item">
                            <ul class="menu_col_list">
                                 {% for subcategory in category.subcategories.all %}
                                    <li class="menu_col_list_item">
                                        <a href="/products/?subcategory={{ subcategory.pk }}">{{ subcategory }}</a>
                                    </li>
                                {% endfor %}
                            </ul>

                </div>
            </div>
        </div>
       {% endfor %}
    </div>

</header>
    </div>