cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('added/<int:product_id>/', views.single_cart_add, name='single_cart_add'),
    path('product/add/<int:product_id>/', views.add_to_card_from_product_page, name='add_to_card_from_product_page'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

orders/urls.py
from django.urls import path

from products.views import ReviewModelSerializerListAPIView, AddRatingViewSet
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('api/v1/reviews/', ReviewModelSerializerListAPIView.as_view()),
    path('api/v1/add-review/', AddRatingViewSet.as_view()),
]

products/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from cart import views
from products.views import ProductTemplate, ProductDetailView, AddReview, WishlistModelListView, add_to_wishlist, \
    CartModelListView, add_to_cart, load_more_data, ProductListAPIView, ProductDiscountAPIView, ProductDetailAPIView, \
    ProductFilterListAPIView, ProductBrandFilterListAPIView

app_name = 'product'

urlpatterns = [
    path('', ProductTemplate.as_view(), name='products'),
    path('<int:pk>/', ProductDetailView.as_view(), name='single'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('products/<int:pk>/', AddReview.as_view(), name='add_review'),
    path('wishlist/', WishlistModelListView.as_view(), name='wishlist'),
    path('wishlist/<int:pk>/', add_to_wishlist, name='add-wishlist'),
    path('cart/', CartModelListView.as_view(), name='cart'),
    path('cart/<int:pk>/', add_to_cart, name='add-cart'),
    path('api/v1/products/', ProductListAPIView.as_view(), name='products'),
    path('api/v1/products/filters-category', ProductFilterListAPIView.as_view(), name='products-filter'),
    path('api/v1/products/filters-brand', ProductBrandFilterListAPIView.as_view(), name='products-filter-brand'),
    path('api/v1/discount/', ProductDiscountAPIView.as_view()),
    path('api/v1/products/<int:pk>/', ProductDetailAPIView.as_view()),

    # path('carts/<int:pk>/', create_carts, name='create-carts'),
]

teiler/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.routers import DefaultRouter
from cart import views
from help.views import HelpListView
from products.serializers import ReviewCreateSerializer
from products.views import HomeTemplate, AboutTemplateView, ContactTemplateView, OrderTemplateView, load_more_data, \
    ProductListAPIView, ProductRatingAPIView, CarouselListAPIView, HelpListAPIView, CategoryListAPIView, \
    ProductDetailAPIView, CountryListAPIView, ProductImageModelAPIView, ProductDiscountAPIView, \
    ReviewModelSerializerListAPIView, AddRatingViewSet
from user.views import edit_account_view, update_username, update_phone, update_email, update_date, \
    update_male, UserViewSet, UserDetailAPIView, UserProductDetail, TokenCreateView, LogoutView, UpdateProfileView, \
    GetProfileView, MyTokenObtainPairView, LoginAPIView, UserNewCreateView
from orders.views import user_order_view, UserAPIListView, OrderAPIListView
from .yasg import urlpatterns as doc_urls


router = DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('products/', include('products.urls',  namespace='product')),
    path('about/', AboutTemplateView.as_view(), name='abouts'),
    path('contacts/', ContactTemplateView.as_view(), name='contacts'),
    path('articles/', HelpListView.as_view(), name='articles'),
    path('order/', OrderTemplateView.as_view(), name='order'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('reviews/', include('orders.urls', namespace='reviews')),
    path('profile/<int:user_pk>', user_order_view, name='profile'),
    path('profilw_edit/<user_id>/edit/', edit_account_view, name='edit'),
    path('change_username/<user_id>/edit/', update_username, name='update_username'),
    path('change_phone/<user_id>/edit/', update_phone, name='update_phone'),
    path('change_email/<user_id>/edit/', update_email, name='update_email'),
    path('change_date/<user_id>/edit/', update_date, name='update_date'),
    path('change_male/<user_id>/edit/', update_male, name='update_male'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('load-more-data/', load_more_data, name='load_more_data'),
    # path('api/v1/auth/', include('djoser.urls.authtoken')),
    # path('api/v1/auth/login/', TokenCreateView.as_view()),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/cities/', CountryListAPIView.as_view()),
    path('users/', include('user.urls')),
    # path('reviewssss/', include('orders.urls', namespace='orders22')),

    path('api/v1/carousels', CarouselListAPIView.as_view()),
    path('api/v1/help', HelpListAPIView.as_view()),
    path('api/v1/categories', CategoryListAPIView.as_view()),
    path('authorizations/', include('authorization.urls')),
    # path('api2/users/', UserAPIListView.as_view()),
    # path('api2/user-order/', OrderAPIListView.as_view()),
    path('', HomeTemplate.as_view())
]

urlpatterns += doc_urls
urlpatterns += router.urls

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from decimal import Decimal

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from coupons.models import Coupon
from products.models import ProductModel
from user.models import CustomUser


class OrderModel(models.Model):
    Online_choices = (
        ("online", "Картой онлайн"),
        ("chache", "Оплата при получении"),
    )
    online = models.CharField(
        max_length=50,
        choices=Online_choices,
        null=True,
        blank=True
    )

    Receiving_choices = (
        ("email", "Получить почтой"),
        ("deliver", "Доставить курьером"),
        ("ru_mail", "Получить из почтамата"),
    )

    upon_receipt = models.CharField(
        max_length=200,
        choices=Receiving_choices,
        null=True,
        blank=True
    )

    Order_choices = (
        ("process", "В процессе"),
        ("cancel", "Заказ отменен"),
        ("delivery", "Выполняется доставка"),
        ("success", "Товар получен"),
    )

    status = models.CharField(
        max_length=200,
        choices=Order_choices,
        null=True,
        default="process",
        blank=True
    )

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='user_order', null=True, blank=True)
    phone = models.CharField(max_length=20, verbose_name='phone', null=True)
    email = models.EmailField(null=True)
    address = models.CharField(max_length=100, verbose_name='address', null=True)
    flat_office = models.CharField(max_length=100, verbose_name='flat_office', null=True)
    entrance = models.CharField(max_length=100, verbose_name='entrance', null=True)
    intercom = models.CharField(max_length=100, verbose_name='intercom', null=True)
    floor = models.CharField(max_length=100, verbose_name='floor', null=True)
    coupon = models.ForeignKey(Coupon, related_name='orders', null=True, blank=True, on_delete=models.SET_NULL)
    discount = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost - total_cost * (self.discount / Decimal('100'))


class OrderItem(models.Model):
    order = models.ForeignKey(OrderModel, related_name='order', on_delete=models.CASCADE)
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms

from .models import OrderModel


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = OrderModel
        label = 'Test'
        fields = ['online', 'upon_receipt', 'status', 'user']
        widgets = {
            'online': forms.RadioSelect(),
            'upon_receipt': forms.RadioSelect(),
            'status': forms.RadioSelect(),
            'user': forms.HiddenInput()
        }

products/forms.py
from django import forms
from django.forms import BaseForm, inlineformset_factory

from products import models
from products.models import ColorModel, ReviewModel, RegisterForm, ProductModel


class ColorModelForm(forms.ModelForm):
    class Meta:
        model = ColorModel
        fields = '__all__'
        widgets = {
            'code': forms.TextInput(
                attrs={'type': 'color'}
            )
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewModel
        fields = ("name", "email", "comments", "rating")


class SingleProductForm(forms.ModelForm):
    class Meta:
        model = ProductModel
        fields = '__all__'

orders/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from drf_yasg.utils import swagger_auto_schema
from rest_framework import status
from rest_framework.generics import ListAPIView
from rest_framework.viewsets import ModelViewSet
from rest_framework.response import Response

from coupons.forms import CouponApplyForm
from products.models import ProductModel
from user.models import CustomUser
from .models import OrderItem, OrderModel
from .forms import OrderCreateForm
from cart.cart import Cart
from .serializers import UserSerializer, OrderItemSerializer


@login_required(login_url="login")
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.phone = request.user.phone
            order.email = request.user.email
            order.user = request.user
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity'],
                )
            coupon_apply_form = CouponApplyForm()
            cart.clear()
            return render(request, 'orders/order/created.html',
                          {'order': order, 'coupon_apply_form': coupon_apply_form})

    else:
        form = OrderCreateForm()
        coupon_apply_form = CouponApplyForm()
        print("invalid")

    return render(request, 'orders/order/create.html',
                  {'form': form, 'cart': cart})


@login_required(login_url="signup")
def user_order_view(request, user_pk):
    user = CustomUser.objects.get(id=user_pk)
    user_orders = user.user_order.all()
    order_items = OrderItem.objects.select_related('product').filter(order__user_id=request.user)

    return render(request, 'lk.html', {'user_orders': user_orders,
                                       'order_items': order_items
                                       })


class UserAPIListView(ModelViewSet):
    queryset = OrderModel.objects.all()
    serializer_class = UserSerializer

    @swagger_auto_schema(
        operation_summary="All infos user",
        operation_description="Methods for All infos user",
    )
    def list(self, request):
        queryset = OrderModel.objects.all()
        serializer = UserSerializer(queryset, many=True)
        return Response(serializer.data)

    @swagger_auto_schema(
        operation_summary="GET user by ID(GET METHOD)",
        operation_description="Methods for GET user by ID(GET METHOD)",
    )
    def retrieve(self, request, pk=None):
        queryset = OrderModel.objects.all()
        user = get_object_or_404(queryset, pk=pk)
        serializer = UserSerializer(user)
        return Response(serializer.data)

    @swagger_auto_schema(
        operation_summary="POST user (POST METHOD)",
        operation_description="Methods for POST user (POST METHOD)",
    )
    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

    def get_serializer_context(self):
        return {'request': self.request}


class OrderAPIListView(ListAPIView):
    queryset = OrderItem.objects.all()
    serializer_class = OrderItemSerializer
# def create_order(request):
#     user = CustomUser
#     if request.method == 'POST':
#         form = OrderCreateForm(request.POST)
#         if form.is_valid():
#             form.save(commit=False)
#             form.cleaned_data['first_name'] = request.user.first_name
#             # form.cleaned_data['address'] = user.addres
#             form.save()
#             print(form)

templates/favs.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load new_tags %}
{% block content %}
        <main class="main">
            <div class="container">
                <div id="favs">
                    <div class="main__content">
                        <div class="favs">
                            <div class="section__top">
                                <h2 class="section_title">Избранное</h2>
                                <!-- <a href="#" class="section__top_link">Показать все</a> -->
                            </div>
            
                            <div class="product_list">
                                {% if object_list %}
                                  {% for product in object_list %}
                                         <div class="product">
                                        <a href="{% url 'product:single' pk=product.pk %}" class="product_img">
                                            <picture>
                                                <source type="image/webp">
                                                <img src="{{ product.image.url }}" style="width: 137px;height: 158px" alt="Product">
                                            </picture>
                                        </a>
                                        <div class="product_rate">

                                            <div class="info">
                                                4
                                                <span>(13)</span>
                                            </div>
                                        </div>
                                        <a href="{% url 'product:single' pk=product.pk %}" class="product_name">{{ product.title }}</a>
                                        <div class="product_price">
                                            <div class="actual">{{ product.real_price }} ₽</div>
                                           {% if product.is_discount %}
                                                 <div class="old">{{ product.price }}</div>
                                            {% endif %}
                                        </div>
                                        <div class="product_btn">
                                           {% if product.is_published == True %}
                                             <a onclick="add_to_cart(this, {{ product.pk }})" style="width: 100%">
                                                     {% if product|in_cart:request %}
                                                            <button class="btn orange-1" type="submit">В корзине</button>
                                                      {% else %}
                                                            <button class="btn" type="submit">В корзину</button>
                                                      {% endif %}
                                                </a>

                                            {% else %}
                                                  <button disabled class="btn btn_dis">Нет в наличии</button>
                                            {% endif %}

                                                 <a onclick="add_to_wishlist(this, {{ product.pk }})">
                                                         <div class="fav2">
                                                             {% if product|in_wishlist:request %}
                                                                  <svg width="10" height="12" viewBox="0 0 10 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0.323242 1.167C0.323242 0.522484 0.846628 0 1.49226 0H8.50635C9.15198 0 9.67537 0.522483 9.67537 1.167V11.0865C9.67537 11.3051 9.553 11.5053 9.35832 11.6053C9.16364 11.7053 8.92929 11.6884 8.75112 11.5613L4.9993 8.88606L1.24749 11.5613C1.06932 11.6884 0.834973 11.7053 0.64029 11.6053C0.445607 11.5053 0.323242 11.3051 0.323242 11.0865V1.167ZM8.50635 1.167L4.65957 7.69419C4.8628 7.54927 5.13581 7.54927 5.33904 7.69419L2 8L8.50635 1.167Z" fill="#FF9700"/></svg>
                                                              {% else %}
                                                                  <svg width="10" height="12" viewBox="0 0 10 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 1.167C0 0.522484 0.522483 0 1.167 0H8.169C8.81351 0 9.336 0.522483 9.336 1.167V11.0865C9.336 11.3051 9.21384 11.5053 9.0195 11.6053C8.82515 11.7053 8.59121 11.6884 8.41335 11.5613L4.668 8.88606L0.922652 11.5613C0.744793 11.6884 0.510848 11.7053 0.316501 11.6053C0.122154 11.5053 0 11.3051 0 11.0865V1.167ZM8.169 1.167L1.167 1.167V9.95265L4.32885 7.69419C4.53173 7.54927 4.80427 7.54927 5.00715 7.69419L8.169 9.95265V1.167Z" fill="#242424"/></svg>
                                                              {% endif %}
                                                          </div>
                                                </a>
                                        </div>
                                          {% if product.is_discount %}
                                              <div class="product_ex">-{{ product.discount }}%</div>
                                        {% endif %}
                                    </div>
                                    {% endfor %}
                                {% else %}
                                 <h3>Избранное пусто</h3>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
               
                
                
                <section class="pop">
                    <div class="section__top">
                        <h2 class="section_title">Для вас</h2>
                        <a href="{% url 'product:products' %}" class="section__top_link">Показать все</a>
                    </div>
    
                    <div class="product_list">
                        {% for product in products %}
                            <div class="product">
                                {% include 'layouts/product-block.html' %}
                            </div>
                       {% endfor %}
                    </div>
                </section>

                <section class="reg">
                    <div class="mainform">
    <h2 class="section_title">Узнавайте об новых акциях</h2>
    <div class="mainform_subtitle">Подпишитесь и получайте промокоды, акции и подборки товаров на свою почту.</div>
    <form class="mainform_body">
        <input type="email" placeholder="Ваш e-mail ">
        <button class="btn" type="submit">Подписаться</button>
    </form>
    <div class="mainform_info">
        Нажимая на кнопку я подтверждаю обработку <a href="#">персональных данных</a>
    </div>
</div>
                    
                </section>
            </div>
        </main>
        <div class="popup" id="login" aria-hidden="true">

    <div class="popup__layer" tabindex="-1" data-micromodal-close>
  
      <!-- [3] -->
      <div role="dialog" aria-modal="true" >
        
        <div class="popup__auth">
          <div class="popup__auth_hi">Здравствуйте!</div>
          <div class="popup__auth_title">
            Войдите в личный кабинет
          </div>

          <form class="popup__auth_form">
              <div class="popup__auth_form_item mail">
                  <label>
                    E-Mail 
                    <div class="inp">
                      <input type="email" placeholder="e.g.: elonmusk@mars.com ">
                    </div>
                  </label>
              </div>

              <div class="popup__auth_form_item pass">
                <label>
                    Ваш пароль
                  <div class="inp">
                    <input type="password" placeholder="e.g.: X Æ A-12 ">
                  </div>
                </label>
            </div>

              <div class="popup__auth_form_btn">
                  <button class="btn">Войти</button>
              </div>
          </form>

          <div class="popup__auth_ex">
            Нет аккаунта? <button id="regButton">Зарегистрироваться →</button>
          </div>
        </div>
  
      </div>
    </div>
  </div>
        <div class="popup" id="signin" aria-hidden="true">

    <div class="popup__layer" tabindex="-1" data-micromodal-close>
  
      <!-- [3] -->
      <div role="dialog" aria-modal="true" >
        
        <div class="popup__auth">
          <div class="popup__auth_hi">Здравствуйте!</div>
          <div class="popup__auth_title">
            Зарегистрируйтесь,что бы войти в личный кабинет
          </div>

          <form class="popup__auth_form">
              <div class="popup__auth_form_item mail">
                  <label>
                    E-Mail 
                    <div class="inp">
                      <input type="email" placeholder="e.g.: elonmusk@mars.com ">
                    </div>
                  </label>
              </div>

              <div class="popup__auth_form_item pass">
                <label>
                    Ваш пароль
                  <div class="inp">
                    <input type="password" placeholder="e.g.: X Æ A-12 ">
                  </div>
                </label>
            </div>

              <div class="popup__auth_form_btn">
                  <button class="btn">Зарегистрироваться</button>
              </div>
          </form>

          <div class="popup__auth_ex">
            Есть аккаунт? <button id="logButton">Войти →</button>
          </div>
        </div>
  
      </div>
    </div>
  </div>
        <div class="popup" id="city" aria-hidden="true">

    <div class="popup__layer" tabindex="-1" data-micromodal-close>
  
      <!-- [3] -->
      <div role="dialog" aria-modal="true" >
        
        <div class="popup__city">
          <h2 class="popup__city_title">
            Выберите город
          </h2>
          <form class="popup__city_form">
            <div class="popup__city_search">
              <select class="popup__city_search_select">
                <option value="Москва">Москва</option>
                <option value="Санкт-Петербург">Санкт-Петербург</option>
                <option value="Екатеринбург">Екатеринбург</option>
              </select>
            </div>
            <button class="popup__city_btn">Сохранить</button>
          </form>
          
        </div>
  
      </div>
    </div>
  </div>
        <div class="popup" id="map-p" aria-hidden="true">

    <div class="popup__layer" tabindex="-1" data-micromodal-close>
  
      <!-- [3] -->
      <div role="dialog" aria-modal="true" >
        
        <div class="map">
            <div class="map_wr">
                <h2 class="map__head">
                    Введите адрес
                </h2>
                <form class="map__form">
                    <div class="map__form_search">
                        <input required class="map__form_search_input" type="text" id="suggest">
                        <button type="button" class="map__form_search_btn" type="submit" id="button">Найти</button>
                    </div>
                    <p class="map__form_notice" id="notice">Адрес не найден</p>
                    <div class="map__form_map" id="map">
    
                    </div>
                </form>
            </div>

            <div class="popup__adress">

                <div id="street-point" class="popup__adress_head dsbl">
                  Улица
                </div>
      
                <div class="popup__adress_scdr dsbl"><span id="city-point">Город</span>, <span id="country-point">Страна</span></div>
      
                <form id="mapForm" class="popup__adress_form">
                    <div class="popup__adress_form_main">
                      <div class="popup__adress_form_main_head">
                        <div class="name">Квартира/Офис</div>
                        <label>
                          <input disabled type="checkbox" class="mapInput">
                          Частный дом
                        </label>
                      </div>
                      <div class="popup__adress_form_main_input">
                        <input disabled required type="text" class="mapInput">
                      </div>
                    </div>
      
                    <div class="popup__adress_form_ex">
                      <div class="popup__adress_form_ex_head">
                        Укажите дополнительную информацию для курьера
                      </div>
                      <div class="popup__adress_form_ex_wr">
                        <div class="item">
                          <input disabled required type="text" placeholder="Укажите подъезд" class="mapInput">
                        </div>
                        <div class="item">
                          <input disabled required type="text" placeholder="Домофон" class="mapInput">
                        </div>
                        <div class="item">
                          <input disabled required type="text" placeholder="Этаж" class="mapInput">
                        </div>
                      </div>
                    </div>
      
                    <div class="popup__adress_form_btn">
                      <button disabled>Выбрать</button>
                    </div>
                </form>
      
              </div>
        </div>

        
  
      </div>
    </div>
  </div>
{% endblock %}

templates/plusminusnumber.html
{% extends 'layouts/base.html' %}

<input type="number" name="{{ widget.name }}" class="form-control quantity-number" value="{{ widget.value }}" min="1" max="10" {% include "django/forms/widgets/attrs.html" %} />
<button type="button" class="btn btn-default btn-number btn-minus" data-type="minus" data-field="{{ widget.name }}"> - </button>
<button type="button" class="btn btn-default btn-number btn-plus" data-type="plus" data-field="{{ widget.name }}"> + </button>